### ISSUE TITLE
关于国服开服后运行佣兵一条龙的流程

### ISSUE THREAD

**Issue by rudolfchen** [z-henry/HSCentric#1]
老哥，您好
碍于完全不会代码及相关环境部署啥的
想详细咨询一下如何配置才能正常运行佣兵一条龙服务，谢谢您。

目前通过琴佬的中控已安装补丁，hsmod已更新到10月19号的。
后续想根据您的项目的要求下载了HSCentric-master，解压复制到相关文件夹。
但是就是运行不起来。
实在没头绪了，就来提issues，盼复，万分感激。

**Comment by z-henry** [comment]
佣兵插件是国服下线时的版本，鉴于目前没有经验了，已经不做维护了。如果想维护可以自行反编译dll
中控还可以搭配琴弦的hb使用
